Mein/Mein/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('infos.urls')),
]

Mein/infos/urls.py
from django.urls import path
from .views import IndexList, MainList, DetailHos, SearchList, DivList

app_name = 'infos'

urlpatterns = [
    path('', IndexList.as_view(), name='index'),
    path('list/<str:region>/', MainList.as_view(), name='list'),
    path('detail/<str:pk>/', DetailHos.as_view(), name='detail'),
    path('search/', SearchList.as_view(), name='search'),
    path('div/', DivList.as_view(), name='div'),
]

Mein/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('infos.urls')),
]

Mein/infos/models.py
from django.db import models

# Create your models here.

class MainInfo(models.Model):
    hpid = models.CharField(primary_key=True, max_length=20)
    name = models.CharField(max_length=200, default='')
    region = models.CharField(max_length=20, default='')
    div = models.CharField(max_length=300, default='')
    subject = models.CharField(max_length=1000, default='')
    tel = models.CharField(max_length=70, default='')
    etel = models.CharField(max_length=70, default='')
    info = models.CharField(max_length=500, default='')
    lat = models.FloatField(default=0)
    lon = models.FloatField(default=0)
    addr = models.CharField(max_length=500, default='')

class SpecialInfo(models.Model):
    hpid = models.ForeignKey(MainInfo, on_delete=models.CASCADE)
    emergency = models.CharField(max_length=4, default='')
    limbs = models.CharField(max_length=4, default='')
    pregnent = models.CharField(max_length=4, default='')
    newborn = models.CharField(max_length=4, default='')
    burn = models.CharField(max_length=4, default='')
    dialysis = models.CharField(max_length=4, default='')

class SubInfo(models.Model):
    hpid = models.ForeignKey(MainInfo, on_delete=models.CASCADE)
    mondayStart = models.CharField(max_length=10, default='')
    mondayEnd = models.CharField(max_length=10, default='')
    tuesdayStart = models.CharField(max_length=10, default='')
    tuesdayEnd = models.CharField(max_length=10, default='')
    wednesdayStart = models.CharField(max_length=10, default='')
    wednesdayEnd = models.CharField(max_length=10, default='')
    thursdayStart = models.CharField(max_length=10, default='')
    thursdayEnd = models.CharField(max_length=10, default='')
    fridayStart = models.CharField(max_length=10, default='')
    fridayEnd = models.CharField(max_length=10, default='')
    saturdayStart = models.CharField(max_length=10, default='')
    saturdayEnd = models.CharField(max_length=10, default='')
    sundayStart = models.CharField(max_length=10, default='')
    sundayEnd = models.CharField(max_length=10, default='')
    holidayStart = models.CharField(max_length=10, default='')
    holidayEnd = models.CharField(max_length=10, default='')

class GradeInfo(models.Model):
    hpid = models.ForeignKey(MainInfo, on_delete=models.CASCADE, default='')
    hurl = models.CharField(max_length=200, default='')
    highblood = models.IntegerField(default=0)
    lungCa = models.IntegerField(default=0)
    stomachCa = models.IntegerField(default=0)
    liverCa = models.IntegerField(default=0)
    bowelCa = models.IntegerField(default=0)
    breastCa = models.IntegerField(default=0)
    cesarean = models.IntegerField(default=0)
    antibiotics = models.IntegerField(default=0)
    injection = models.IntegerField(default=0)
    diabetes = models.IntegerField(default=0)
    asthma = models.IntegerField(default=0)
    dialysis = models.IntegerField(default=0)

Mein/infos/views.py
from django.shortcuts import render
from .models import MainInfo, SubInfo, GradeInfo, SpecialInfo
from django.views import generic
from django.core.paginator import Paginator
from django.db.models import Q

# Create your views here.

class IndexList(generic.ListView):
    template_name = 'main.html'
    context_object_name = "main_list"
    paginate_by = 5
    queryset = MainInfo.objects.filter(region='강남구')

    def get_context_data(self, **kwargs):
        context = super(IndexList, self).get_context_data(**kwargs)
        paginator = context['paginator']
        page_numbers_range = 10
        max_index = len(paginator.page_range)

        page = self.request.GET.get('page')
        current_page = int(page) if page else 1

        start_index = int((current_page - 1) / page_numbers_range) * page_numbers_range
        end_index = start_index + page_numbers_range
        if end_index >= max_index:
            end_index = max_index

        page_range = paginator.page_range[start_index:end_index]
        context['page_range'] = page_range
        context['max_index'] = max_index
        return context


class MainList(generic.ListView):
    template_name = 'main.html'
    context_object_name = "main_list"
    paginate_by = 5

    def get_queryset(self):
        return MainInfo.objects.filter(region=self.kwargs['region'])

    def get_context_data(self, **kwargs):
        context = super(MainList, self).get_context_data(**kwargs)
        paginator = context['paginator']
        page_numbers_range = 10
        max_index = len(paginator.page_range)

        page = self.request.GET.get('page')
        current_page = int(page) if page else 1

        start_index = int((current_page - 1) / page_numbers_range) * page_numbers_range
        end_index = start_index + page_numbers_range
        if end_index >= max_index:
            end_index = max_index

        page_range = paginator.page_range[start_index:end_index]
        context['page_range'] = page_range
        context['max_index'] = max_index
        context['region'] = self.kwargs['region'] if self.kwargs['region'] else '강남구'
        print('region', context['region'])
        return context


class DetailHos(generic.DetailView):
    model = MainInfo
    template_name = 'detail.html'

class SearchList(generic.ListView):
    template_name = 'main.html'
    context_object_name = "main_list"
    paginate_by = 5

    def get_queryset(self):
        topic = self.request.GET.get('topic')
        keyword = self.request.GET.get('keyword')

        if topic == 'name':
            return MainInfo.objects.filter(name__contains=keyword)
        elif topic == 'addr':
            return MainInfo.objects.filter(addr__contains=keyword)
        else:
            return MainInfo.objects.filter(tel__contains=keyword)

    def get_context_data(self, **kwargs):
        context = super(SearchList, self).get_context_data(**kwargs)
        paginator = context['paginator']
        page_numbers_range = 10
        max_index = len(paginator.page_range)

        page = self.request.GET.get('page')
        current_page = int(page) if page else 1

        start_index = int((current_page - 1) / page_numbers_range) * page_numbers_range
        end_index = start_index + page_numbers_range
        if end_index >= max_index:
            end_index = max_index

        page_range = paginator.page_range[start_index:end_index]
        context['page_range'] = page_range
        context['max_index'] = max_index
        context['topic'] = self.request.GET.get('topic')
        context['keyword'] = self.request.GET.get('keyword')
        return context

class DivList(generic.ListView):
    template_name = 'checkMain.html'
    context_object_name = "main_list"
    paginate_by = 5

    def get_queryset(self):
        special_q = None
        day_q = None
        sub_q = None
        sub = 0  if not self.request.GET.get('sub') else self.request.GET.get('sub')
        spec = 0 if not self.request.GET.get('spec') else self.request.GET.get('spec')
        day = 0 if not self.request.GET.get('day') else self.request.GET.get('day')

        if spec != 0 :
            if '응급실' in spec : special_q = Q(emergency='Y') if special_q is None else special_q & Q(emergency='Y')
            if '사지접합' in spec : special_q = Q(limbs='Y') if special_q is None else special_q & Q(limbs='Y')
            if '신생아' in spec : special_q = Q(newborn='Y') if special_q is None else special_q & Q(newborn='Y')
            if '조산산모' in spec : special_q = Q(pregnent='Y') if special_q is None else special_q & Q(pregnent='Y')
            if '화상' in spec : special_q = Q(burn='Y') if special_q is None else special_q & Q(burn='Y')
            if '응급투석' in spec : special_q = Q(dialysis='Y') if special_q is None else special_q & Q(dialysis='Y')
            special_list = SpecialInfo.objects.filter(special_q).values_list('hpid', flat=True)
            special_q = None
            for special_hp in special_list:
                special_q = Q(hpid=special_hp) if special_q is None else special_q | Q(hpid=special_hp)

        if day != 0 :
            if '토요일' in day : day_q = Q(saturdayStart__contains='0') if day_q is None else day_q & Q(saturdayStart__contains='0')
            if '일요일' in day : day_q = Q(sundayStart__contains='0') if day_q is None else day_q & Q(sundayStart__contains='0')
            if '공휴일' in day : day_q = Q(holidayStart__contains='0') if day_q is None else day_q & Q(holidayStart__contains='0')
            day_list = SubInfo.objects.filter(day_q).values_list('hpid', flat=True)
            day_q = None
            for day_hp in day_list:
                day_q = Q(hpid=day_hp) if day_q is None else day_q | Q(hpid=day_hp)

        if sub != 0:
            for s in sub.split(","):
                sub_q = Q(subject__contains=s) if sub_q is None else sub_q & Q(subject__contains=s)

        if special_q is None : special_q = Q(name__contains="")
        if day_q is None : day_q = Q(name__contains="")
        if sub_q is None : sub_q = Q(name__contains="")

        main_q = special_q & day_q & sub_q

        return MainInfo.objects.filter(main_q)

    def get_context_data(self, **kwargs):
        context = super(DivList, self).get_context_data(**kwargs)
        paginator = context['paginator']
        page_numbers_range = 10
        max_index = len(paginator.page_range)

        page = self.request.GET.get('page')
        current_page = int(page) if page else 1

        start_index = int((current_page - 1) / page_numbers_range) * page_numbers_range
        end_index = start_index + page_numbers_range
        if end_index >= max_index:
            end_index = max_index

        page_range = paginator.page_range[start_index:end_index]
        context['page_range'] = page_range
        context['max_index'] = max_index
        if self.request.GET.get('sub') : context['sub'] = self.request.GET.get('sub')
        if self.request.GET.get('spec'): context['spec'] = self.request.GET.get('spec')
        if self.request.GET.get('day') : context['day'] = self.request.GET.get('day')
        return context

Mein/infos/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <title>Mein</title>

    <!-- Custom styles for this template -->
    <link href="https://fonts.googleapis.com/css?family=Playfair+Display:700,900" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Jua" rel="stylesheet">
    <style>
        div{
          font-family: 'Jua', 'Playfair';
        }
       a{
          text-decoration: none !important;
        }
    </style>
    <script type="text/javascript" src="https://openapi.map.naver.com/openapi/v3/maps.js?clientId=lMn2JmpHyO4i3aU9LiHe&submodules=geocoder"></script>
  </head>

  <body>
    <div class="container">
      <header class="blog-header py-3">
        <div class="row flex-nowrap justify-content-between align-items-center">
          <div class="col-4 pt-1">
            <span>Medical + Information</span>
          </div>
          <div class="col-4 text-center">
            <h2><a class="blog-header-logo text-primary" href="{% url 'infos:index' %}">Mein</a></h2>
          </div>
          <div class="col-4 d-flex justify-content-end align-items-center">
            <a class="text-muted" href="#" data-toggle="modal" data-target="#searchModal">
              <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="mx-3"><circle cx="10.5" cy="10.5" r="7.5"></circle><line x1="21" y1="21" x2="15.8" y2="15.8"></line></svg>
            </a>
            <a class="btn btn-sm btn-outline-secondary" href="#" data-toggle="modal" data-target="#regionListModal">Region List</a>
            {% block listbtn %} {% endblock listbtn %}
          </div>
        </div>
      </header>

      <!-- searchModal -->
      <div class="modal fade" id="searchModal" tabindex="-1" aria-hidden="true">
        <div class="modal-dialog" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title">Search</h5>
            </div>
            <form action="{% url 'infos:search' %}" method="get">
            <div class="modal-body">
             <div class="input-group mb-3">
              <div class="input-group-prepend">
                 <select name="topic" class="custom-select">
                  <option selected>--분류--</option>
                  <option value="name">병원명</option>
                  <option value="addr">주소</option>
                  <option value="tel">전화번호</option>
                 </select>
              </div>
              <input name="keyword" type="text" class="form-control" placeholder="Keyword input" required>
               <div class="input-group-append">
                  <input class="btn btn-outline-secondary" type="submit" value="검색"/>
               </div>
              </div>
            </div>
            </form>
            <div class="modal-footer">
              <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            </div>
          </div>
        </div>
      </div>
      <!-- end searchModal -->

      <!-- searchModal -->
      <div class="modal fade" id="regionListModal" tabindex="-1" aria-hidden="true">
        <div class="modal-dialog" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title">Region List</h5>
            </div>
            <div class="modal-body">
              <div class="row">
                <div class="col-3 border-right">
                  <div class="nav flex-column nav-pills" role="tablist" aria-orientation="vertical">
                    <a class="nav-link active" data-toggle="pill" href="#seoul_list" role="tab" >서울</a>
                    <a class="nav-link" data-toggle="pill" href="#incheon_list" role="tab" >인천</a>
                    <a class="nav-link" data-toggle="pill" href="#v-pills-messages" role="tab" >경기도</a>
                    <a class="nav-link" data-toggle="pill" href="#v-pills-settings" role="tab" >충청도</a>
                  </div>
                </div>
                <div class="col-9">
                  <div class="tab-content">
                    <div class="tab-pane fade show active" id="seoul_list" role="tabpanel">
                      <a class="btn btn-outline-secondary mr-2 mb-2" href="{% url 'infos:list' '강남구' %}" >서울 강남구</a>
                      <a class="btn btn-outline-secondary mr-2 mb-2" href="{% url 'infos:list' '서초구' %}" >서울 서초구</a>
                      <a class="btn btn-outline-secondary mr-2 mb-2" href="{% url 'infos:list' '송파구' %}" >서울 송파구</a>
                      <a class="btn btn-outline-secondary mr-2 mb-2" href="{% url 'infos:list' '종로구' %}" >서울 종로구</a>
                      <a class="btn btn-outline-secondary mr-2 mb-2" href="{% url 'infos:list' '강서구' %}" >서울 강서구</a>
                    </div>
                    <div class="tab-pane fade" id="incheon_list" role="tabpanel">
                      <a class="btn btn-outline-secondary mr-2 mb-2" href="#" >인천 계양구</a>
                      <a class="btn btn-outline-secondary mr-2 mb-2" href="#" >인천 남구</a>
                    </div>
                  </div> <!-- div.tap-content -->
                </div> <!-- div.col-9 -->
              </div> <!-- div.row -->
            </div> <!-- modal-body -->

            <div class="modal-footer">
              <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            </div>
          </div>
        </div>
      </div>
      <!-- end searchModal -->

      <!--Main map-->
      {% block mapname %}
      <h3 class="d-inline">
        서울 {% if region %}{{ region }}{% else %}강남구{% endif %} 지역 지도
      </h3>
      {% endblock mapname %}
      {% block mapinfo %}
      <div class="float-right">
        <i class="fas fa-map-marker-alt text-primary mr-1" style="font-size:22px;"></i>
        <span class="mr-2" style="font-size:107%;">현재위치</span>
        <img id="marker_info" src="{% static 'img/marker_hs2.png'%}"> 마커를 클릭하면 해당 병원정보를 볼 수 있습니다!
      </div>
      {% endblock %}


      <div id="map" class="mb-4 rounded" style="height:400px;">
      </div>
      <!--end Main map-->

    {% block content %}
    {% endblock content %}

      <footer class="blog-footer mt-4">
        <div class="jumbotron p-3 p-md-5 rounded">
          <div class="row">
            <div class="col">
              <h5><i class="fas fa-map-marker-alt mr-2 mt-1"></i><span class="text-primary">서울특별시 서초구 서초1동 효령로 335</span></h5>
              <h5><i class="fas fa-envelope mr-2 mt-2"></i><a href="mailto:perfectwan8765@gmail.com">perfectwan8765@gmail.com</a></h5>
              <h5><i class="fab fa-github mr-2 mt-2"></i><a href="https://github.com/wjdtkddhks/mein.git" target="_blank"
                >https://github.com/wjdtkddhks/mein</a></h5>
            </div>
            <div class="col">
              <h4>About this version</h4>
              <p class="mb-0">
                Period : 2018.11.05~ </br>
                Data_range : 서울 강남구, 서초구, 송파구, 종로구, 강서구 </br>
                Function : Main, ListView, DetailView, Search, Selected keyword List </br>
              </p>
            </div>

          </div>
        </div>
      </footer>

    </div> <!-- end container -->
    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="http://code.jquery.com/jquery-3.1.1.min.js"></script>
    <script src="{% static 'bootEx/popper.js' %}"></script>
    <link rel="stylesheet" href="{% static 'bootEx/bootstrap.min.css' %}">
    <script src="{% static 'bootEx/bootstrap.min.js' %}"></script>
    <script src="{% static 'bootEx/holder.js' %}"></script>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css" integrity="sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU" crossorigin="anonymous">

    {% block soruceAdd %} {% endblock soruceAdd %}
    <script>
      Holder.addTheme('thumb', {
        bg: '#55595c',
        fg: '#eceeef',
        text: 'Thumbnail'
      });

      $(function () {
        $('[data-toggle="popover"]').popover()
        $('[data-toggle="popover"]').hover(function(){$(this).css("cursor", "pointer")},
                                            function(){$(this).css("cursor", "none")});
      });
    </script>
    <style>
      #marker_info{
        border: 0px solid transparent;
        width: 25px;
        height: 25px;
      }
    </style>
  </body>
</html>

Mein/infos/templates/checkMain.html
{% extends 'main.html' %}
{% load static %}

{% block mapname %}
      <h3 class="d-inline">
        {% if topic %}
        지도 검색키워드 : {{ keyword }}
        {% elif sub or day or spec %}
        지도 검색키워드 : {{ sub|default_if_none:"" }} {{ day|default_if_none:"" }} {{ spec|default_if_none:"" }}
        {% else %}
        서울 {% if region %}{{ region }}{% else %}강남구{% endif %} 지역 지도
        {% endif %}
      </h3>
{% endblock mapname %}


{% block listname %}
            <h5 class="d-inline text-primary">
              {% if topic %}
              검색키워드 : {{ keyword }}
              {% elif sub or day or spec %}
              검색키워드 : {{ sub|default_if_none:"" }} {{ day|default_if_none:"" }} {{ spec|default_if_none:"" }}
              {% else %}
              서울 {% if region %}{{ region }}{% else %}강남구{% endif %}
              {% endif %}
            </h5>
{% endblock listname %}


{% block pagination %}
        {% if is_paginated %}
          <nav class="blog-pagination" style="text-align:center;">
            {% if page_obj.has_previous %}
              <a class="btn btn-outline-default"
                 href="?page={{ page_obj.previous_page_number}}{% if day %}&day={{ day }}{% endif %}{% if spec %}&spec={{ spec }}{% endif %}{% if sub %}&sub={{ sub }}{% endif %}"><<</a>
            {% else %}
            <a class="btn btn-outline-default"><<</a>
            {% endif %}

            {% for i in page_range %}
              {% if page_obj.number == i %}
              <a class="btn btn-outline-primary active">{{ i }}</a>
              {% else %}
                <a class="btn btn-outline-primary" href="?page={{i}}{% if day %}&day={{ day }}{% endif %}{% if spec %}&spec={{ spec }}{% endif %}{% if sub %}&sub={{ sub }}{% endif %}">{{ i }}</a>
              {% endif %}
            {% endfor %}

            {% if page_obj.has_next %}
              <a class="btn btn-outline-default" href="?page={{ page_obj.next_page_number}}{% if day %}&day={{ day }}{% endif %}{% if spec %}&spec={{ spec }}{% endif %}{% if sub %}&sub={{ sub }}{% endif %}">>></a>
            {% else %}
            <a class="btn btn-outline-default">>></a>
            {% endif %}

          </nav>
        {% endif %}


{% endblock pagination %}